Repository jasoneri/ComicGUISpider, pull requests merged in 2025-04, with the labels that each got.

#29 [V2.1 dev] 沿用gh-page分支做github page
  .github/workflows/gh_pages.yml
  .github/workflows/release.yml
  .gitignore
  GUI/gui.py
  GUI/uic/qfluent/action_factory.py
  README.md
  assets/qtErr/1.png
  deploy/update.py
  docs/.vitepress/config.ts
  docs/.vitepress/theme/Layout.vue
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/style.css
  docs/CONTRIBUTING/i18n.md
  docs/CONTRIBUTING/spider.md
  docs/FAQ_and_EXTRA.md
  docs/_github/README_en.md
  docs/assets/img/config/conf_usage.png
  docs/assets/img/config/conf_usage_en.png
  docs/assets/img/deploy/mac-app-move.jpg
  docs/assets/img/dev/branch.png
  docs/assets/img/faq/ditto_settings.png
  docs/assets/img/feature/browser_copyBtn.png
  docs/assets/img/icons/website/copy.png
  docs/assets/img/icons/website/ehentai.png
  docs/assets/img/icons/website/jm.png
  docs/assets/img/icons/website/mangabz.png
  docs/assets/img/icons/website/wnacg.png
  docs/changelog/history.md
  docs/config/index.md
  docs/deploy/mac-required-reading.md
  docs/deploy/quick-start.md
  docs/dev/contribute.md
  docs/dev/dev_spider.md
  docs/dev/i18n.md
  docs/faq/extra.md
  docs/faq/index.md
  docs/faq/other.md
  docs/feature/index.md
  docs/feature/script.md
  docs/home/index.md
  docs/index.md
  docs/locate/en/config/index.md
  docs/locate/en/deploy/quick-start.md
  docs/locate/en/index.md
  docs/package.json
  docs/public/CGS-girl.png
  docs/public/_redirects
Labels: documentation

#30 fix: Github Action Error
  .github/workflows/gh_pages.yml
  .github/workflows/release.yml
  .github/workflows/schedule_test.yml
  README.md
  deploy/packer.py
  docs/dev/contribute.md
  docs/locate/en/index.md
  docs/package.json
Labels: bug

#33 V2.2 dev
  .github/workflows/schedule_test.yml
  .gitignore
  ComicSpider/pipelines.py
  ComicSpider/spiders/basecomicspider.py
  ComicSpider/spiders/ehentai.py
  ComicSpider/spiders/hitomi.py
  ComicSpider/spiders/jm.py
  ComicSpider/spiders/kaobei.py
  ComicSpider/spiders/mangabz.py
  ComicSpider/spiders/wnacg.py
  GUI/browser_window.py
  GUI/gui.py
  GUI/hitomi_tools.py
  GUI/mainwindow.py
  GUI/src/preview_format/index.html
  GUI/src/preview_format/index_by_clip.html
  GUI/src/preview_format/public.css
  GUI/src/preview_format/public.js
  GUI/thread/other.py
  GUI/uic/qfluent/action_factory.py
  GUI/uic/qfluent/components.py
  GUI/uic/qfluent/patch_uic.py
  README.md
  assets/res/__init__.py
  assets/res/locale/en-US.yml
  assets/res/locale/en-US/LC_MESSAGES/res.mo
  assets/res/locale/zh-CN.yml
  assets/res/locale/zh-CN/LC_MESSAGES/res.mo
  assets/res/transfer.py
  crawl_only.py
  deploy/env_record.json
  docs/_github/README_en.md
  docs/_github/release_notes.md
  docs/assets/img/icons/website/hitomi.png
  docs/changelog/history.md
  docs/config/index.md
  docs/dev/dev_spider.md
  docs/dev/i18n.md
  docs/feature/index.md
  docs/index.md
  docs/locate/en/config/index.md
  docs/locate/en/index.md
  requirements/mac_arm64.txt
  requirements/mac_x86_64.txt
  requirements/win.txt
  utils/preview/__init__.py
  utils/preview/el.py
  utils/processed_class.py
  utils/website/__init__.py
  utils/website/core.py
  utils/website/hitomi/__init__.py
  utils/website/hitomi/scape_dataset.py
  variables/__init__.py
Labels: enhancement
